//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyRentalManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentId { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime Time { get; set; }
        public int UnitId { get; set; }
        public int UserId { get; set; }
    
        public virtual Unit Unit { get; set; }
        public virtual User User { get; set; }
    }
}
