//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyRentalManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Message
    {
        public int MessageId { get; set; }
        [Display(Name = "Message")]
        public string Message1 { get; set; }
        [Display(Name = "Sender")]
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
